# Generated by Django 2.0.2 on 2018-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldetails',
            name='advance_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='tour_id',
            field=models.IntegerField(null=True),
        ),
    ]
