# Generated by Django 2.0.2 on 2018-03-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180311_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
