# Generated by Django 2.0.2 on 2018-03-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20180311_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldetails',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
