# Generated by Django 2.0.2 on 2018-03-11 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20180311_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('receipt', models.FileField(max_length=50, upload_to='')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
