# Generated by Django 2.0.2 on 2018-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20180314_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='approval',
            field=models.CharField(default='None', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='approval',
            field=models.CharField(default='None', max_length=5, null=True),
        ),
    ]
