# Generated by Django 2.0.2 on 2018-03-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20180315_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='approval',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='traveldetails',
            name='approval',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
    ]
